site_name: 未央学习

repo_url: https://github.com/WeYoung-learn/WeYoung-learn.github.io
repo_name: WeYoung-learn

theme:
  name: 'material'
  language: zh
  icon:
    logo: material/file-document
  palette:
    primary: light blue
  features:
    - navigation.instant
    - navigation.tabs
    - navigation
    - navigation.top

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 首页:
    - 欢迎来到未央学习: "index.md"
    - 随便谢谢: "author.md"
  - 课程笔记:
    - 首页: "course/index.md"
  - 作业攻略:
    - 首页: "homework/index.md"
  - 资源分享: "resource/index.md"